# Generated by Django 5.1.2 on 2024-11-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'PlacesModel',
            },
        ),
    ]
