# Generated by Django 5.1.2 on 2024-11-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_placesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesmodel',
            name='places',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='placesmodel',
            name='restaurants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='placesmodel',
            name='rooms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
