# Generated by Django 5.1.2 on 2024-11-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_placesmodel_places_placesmodel_restaurants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesmodel',
            name='placetype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
