# Generated by Django 5.1.2 on 2024-11-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_placesmodel_placetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.FileField(upload_to='static\\bookingimages')),
            ],
            options={
                'db_table': 'BookingModel',
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.FileField(upload_to='static\\cartimages')),
            ],
            options={
                'db_table': 'CartModel',
            },
        ),
    ]
