# Generated by Django 5.1.2 on 2024-11-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bookingmodel_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
