# Generated by Django 5.1.2 on 2024-11-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bookingmodel_email_cartmodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(null=True)),
                ('placename', models.CharField(max_length=100)),
                ('rating', models.IntegerField(null=True)),
                ('feedback', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'FeedbackModel',
            },
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='pid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='pid',
            field=models.IntegerField(null=True),
        ),
    ]
