# Generated by Django 5.1.2 on 2024-11-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_feedbackmodel_bookingmodel_pid_cartmodel_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
